### ISSUE TITLE
Errors in some case

### ISSUE THREAD

**Issue by sickmitch** [yoyurec/logseq-awesome-ui#74]
**Info:**
- OS: Archlinux up to date
- Logseq ver: logseq-desktop-wayland-bin 0.9.19
- Plugin ver: 2.4.0
- Theme name: catppuccin mocha

- [ x ] ⚠ Do i have issue with DISABLED my `custom.css`?
custom.css is empty

**Description:**
With the plugin enabled i get an error while navigating most recent pages, tried to understand what is the trigger but didn't manage to find it. Disabling the plugin, relaunching logseq and re-enabling it makes it work for sometime but errors will come back. Keeping the plugin disabled solve the error.

**To Reproduce:**
 Create a new page and navigate to it.

**Expected behavior:**
 Entering the page

**Screenshots**
![20231025_09h28m03s_grim](https://github.com/yoyurec/logseq-awesome-ui/assets/134487828/2b993a14-e78a-4735-8a31-e23b30fd8651)

**Attach files**
Can't find logs or whatever usefull on the system, if anything is needed i'm happy to help

**Comment by shyney7** [comment]
I have the same issue!

**Comment by targetblank** [comment]
I can confirm this issue, too. 
- logseq 0.9.2.0
- Awesome UI 2.4.0
- logseq-dev-theme 1.26.17

Error Message in popup after any click on an link while Awesome UI is enabled:

> Error caught by UI!
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

**Comment by sickmitch** [comment]
Update:
Tried out for a couple of days now, after an update to catppuccin theme seems like the problem did fix himself.
*Hoping this is solved for everyone*

**Comment by NickRahn** [comment]
I am getting this same error. I do not have a custom css and am using default theme. I have rebuilt search index, cleared the cache and disabled all other plugins and still get the error.

**Comment by netizen112** [comment]
Still getting this error, on both windows and ubuntu

**Comment by RenegadeScooter** [comment]
Linux Mint user here, having this problem as well

**Comment by Voronenko** [comment]
Issue has to be reopened.

Just to confirm, got the same issue eventually next day, after I decided to give Awesome UI plugin a try.
Issue started to occur, on some random existing tag I used in my note, and after that only resetting state and removing the plugin heals the issue

logseq 0.10.9
awesome ui 2.4.0
no custom css
default theme

**Comment by pedroribeiro1718** [comment]
This is still reproducible. I'm on Linux.

It pops up a notification with the following error:

Error caught by UI!
NotFoundError: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

![Image](https://github.com/user-attachments/assets/383f368e-9eb6-43b1-ac66-ef4dfbdc0538)

This is irrespective of themes or installed plugins. I have a nearly-vanilla installation. Installing Tabs and the Awesome-UI plugin is enough to trigger the error, even on a new installation of Logseq, with no modified settings.

Will be happy to provide logs or more information if needed.
